name: safsofa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.19+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.4
  firebase_core: ^2.16.0
  firebase_core_platform_interface: ^4.5.3
  cloud_firestore: ^4.3.1
  flutter_chat_bubble:
  firebase_messaging: ^14.2.1
  dropdown_button2: ^2.3.9

  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.4+7
  share_plus:
  flutter_svg: ^2.0.3
  path_provider: ^2.0.11
  expansion_tile_card: ^2.0.0
  carousel_slider: ^4.0.0
  syncfusion_flutter_signaturepad: ^22.2.12
 #flutter_native_splash: ^2.2.16
  #carousel_pro: ^1.0.0
  #internet
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  awesome_dialog: ^3.0.2
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  photo_view: ^0.14.0
  animated_conditional_builder: ^0.0.5
  pinch_zoom: ^2.0.0
  easy_image_viewer: ^1.2.1
  dropdown_search: ^5.0.6
  syncfusion_flutter_sliders: ^22.2.12
  flutter_pw_validator: ^1.6.0
  geolocator: ^10.1.0
  pretty_dio_logger: ^1.3.1
  pin_code_fields: ^8.0.1
  in_app_update: ^4.2.2
  upgrader: ^8.4.0
  package_info: ^2.0.2
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.4.4
  intl_phone_field: ^3.2.0
  flutter_paytabs_bridge: ^2.6.7
  go_router: ^13.1.0
  firebase_dynamic_links: ^5.3.7
#  new_version: ^0.3.1
#  version_check: ^0.4.0

dev_dependencies:
  appinio_video_player: ^1.2.0
  conditional_builder_null_safety: ^0.0.6
  devicelocale:
  dio: ^5.0.0
  easy_localization: ^3.0.0
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.0.8
  geocoding: ^2.0.1
  google_maps_flutter: ^2.0.11
  location: ^4.2.0
  map_picker: ^0.0.3
#  map_pin_picker:
  nil: null
  persistent_bottom_nav_bar: any
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.8
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.9
  video_player: ^2.8.1
  youtube_player_flutter: ^8.0.0
  search_map_place_updated: ^0.0.4
  card_swiper: ^2.0.4
  intl:
  badges: ^3.1.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_ic.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
    - family: arial
      fonts:
        - asset: assets/fonts/arail/ArialCEMTBlack.ttf
        - asset: assets/fonts/arail/ArialCEItalic.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
