


abstract class TechnicalSupportDetailstState {}

class TechnicalSupportdetailstInitial extends TechnicalSupportDetailstState {}

class GetTechnicalSupportdetailstLoadingState extends TechnicalSupportDetailstState{}

class GetTechnicalSupportdetailstSuccessState extends TechnicalSupportDetailstState{}

class GetTechnicalSupportdetailstErrorState extends TechnicalSupportDetailstState{}
